const translations: Record<string, string> = {
  currentValue: 'Wartość rynkowa',
  costBasis: 'Koszt nabycia',
  profit: 'Zysk/Strata',
  profitPercent: 'Zwrot',
  quantity: 'Ilość',
  accounts: 'Konta',
  currency: 'Waluta',
  totalValue: 'Wartość łączna',
  assetsCount: 'Aktywa',
  asset: 'Aktywo',
  effectiveValue: 'Wartość efektywna',
  actualPercent: 'Faktyczny udział',
  targetPercent: 'Cel',
  drift: 'Odchylenie',
  name: 'Nazwa',
  type: 'Typ',
  parent: 'Rodzic',
  actions: 'Akcje',
  description: 'Opis',
  percentage: 'Procent',
  bank: 'Instytucja',
  isFree: 'Czy darmowe?',
  conditions: 'Warunki',
  startDate: 'Data rozpoczęcia',
  duration: 'Czas trwania',
  durationEndDate: 'Data zakończenia',
  isActive: 'Czy aktywne?',
  date: 'Data',
  value: 'Wartość',
  vsPrev: 'vs poprzedni',
  vsPrevPercent: 'vs poprzedni %',
  vsFirst: 'vs pierwszy',
  vsFirstPercent: 'vs pierwszy %',
  year: 'Rok',
  startValue: 'Wartość pocz.',
  endValue: 'Wartość końc.',
  netInvested: 'Netto wpłacone',
  gain: 'Zysk/Strata',
  returnPercent: 'Zwrot',
  gainPercent: 'Zwrot',
  amount: 'Kwota',
  counterparty: 'Kontrahent',
  account: 'Konto',
  category: 'Kategoria',
  toAccount: 'Konto docelowe',
  createdAt: 'Systemowa data utworzenia',
  updatedAt: 'Systemowa data aktualizacji',
}

export const tableColumnsTranslate = (columnName: string) =>
  translations[columnName] ?? columnName
