const translations: Record<string, string> = {
  currentValue: 'Wartość',
  accounts: 'Konta',
  currency: 'Waluta',
  totalValue: 'Wartość łączna',
  assetsCount: 'Aktywa',
  asset: 'Aktywo',
  effectiveValue: 'Wartość efektywna',
  actualPercent: 'Faktyczny %',
  targetPercent: 'Cel %',
  drift: 'Odchylenie %',
  name: 'Nazwa',
  type: 'Typ',
  parent: 'Rodzic',
  actions: 'Akcje',
  description: 'Opis',
  percentage: 'Procent',
  bank: 'Bank',
  isFree: 'Czy darmowe?',
  conditions: 'Warunki',
  startDate: 'Data rozpoczęcia',
  duration: 'Czas trwania',
  durationEndDate: 'Data zakończenia',
  isActive: 'Czy aktywne?',
  date: 'Data',
  amount: 'Kwota',
  counterparty: 'Kontrahent',
  account: 'Konto',
  category: 'Kategoria',
  toAccount: 'Konto docelowe',
  createdAt: 'Systemowa data utworzenia',
  updatedAt: 'Systemowa data aktualizacji',
}

export const tableColumnsTranslate = (columnName: string) =>
  translations[columnName] ?? columnName
